language: java
sudo: false
dist: trusty
install: true
addons:
  sonarcloud:
    organization: "ldh-yolo-team"
    token:
      secure: "2111eb579d4959d145da2959cf915f82275b3160"
jdk:
  - oraclejdk8
script:
# the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
#JaCoCo is used to have code coverage, the agent has to be activated
  - echo -e '<?xml version="1.0" encoding="UTF-8"?>\n<settings xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.1.0 http://maven.apache.org/xsd/settings-1.1.0.xsd" xmlns="http://maven.apache.org/SETTINGS/1.1.0"\n    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">\n  <mirrors>\n    <mirror>\n      <id>mvnsearch-unavailable</id>\n      <name>mvnsearch-unavailable</name>\n      <mirrorOf>mvnsearch</mirrorOf>\n      <url>http://repo1.maven.org/maven2</url>\n    </mirror>\n  </mirrors>\n  <profiles>\n    <profile>\n      <id>no-mvnsearch</id>\n      <repositories>\n        <repository>\n          <id>mvnsearch</id>\n          <url>http://www.mvnsearch.org/maven2</url>\n          <releases>\n            <enabled>true</enabled>\n          </releases>\n          <snapshots>\n            <enabled>true</enabled>\n          </snapshots>\n        </repository>\n      </repositories>\n    </profile>\n  </profiles>\n  <activeProfiles>\n    <activeProfile>no-mvnsearch</activeProfile>\n  </activeProfiles>\n</settings>' > $HOME/.m2/settings.xml
  - cat $HOME/.m2/settings.xml
  - mvn clean test org.jacoco:jacoco-maven-plugin:prepare-agent package javadoc:javadoc
  - sonar-scanner
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
    - .autoconf
    - $HOME/.m2
notifications:
  email: 
  recipients:
    - dcastell@ull.es
on_success: always
on_failure: always
